name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven Build & Test (JaCoCo)
        run: mvn -B clean verify

      - name: Upload Test & Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/site/jacoco/
            target/surefire-reports/
          if-no-files-found: ignore
          retention-days: 7

      - name: Generate Coverage Badges
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Commit Coverage Badges
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add *.svg
            git commit -m "chore: update coverage badges"
            git push
          fi

      - name: Coverage Summary
        if: always()
        run: |
          echo "## Coverage (raw HTML footer snippet)" >> $GITHUB_STEP_SUMMARY
          grep -E "<tfoot>" -A3 target/site/jacoco/index.html || true

  mutation:
    name: Mutation Test (PIT)
    runs-on: ubuntu-latest
    timeout-minutes: 40
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run PIT
        run: mvn -B org.pitest:pitest-maven:mutationCoverage
      - name: Upload PIT Report
        uses: actions/upload-artifact@v4
        with:
          name: pit-report
          path: "target/pit-reports"
          retention-days: 7